tinput = """
wwwnwwwwwwwwenwwwwwwww
swwwswswswswswswwswswswneswswswwswse
nenenesenewnenenesenesenenenenenewnewnene
seseswseseswseswwswseswseseseseneswseswse
nwnwsenwnwnwnwnenwnenwnwnwsenenwsenwnwnwne
swswswwswnewswswsw
eneeswnenenweesenenenwneneneeenene
wnwwnwwnwsewnwwnwnwwnwwwnwwnwnw
nwneswsenewenwnwswneswnenenwenwnenenwnwnw
senewnwwwwwwnwwwnwnwnwnwnwwwew
eewneneneeeeneeese
eneewseeneswnweswnwswsw
swwswswseswnwneseswseenwwsesesenewne
swswswswswswseswswseswswsenwsesesenwsee
esesenwnwnwseseneeswseswnwwewesesee
neenenwneswneneneeneneeweneneneswne
eeswswwwsesesenwswswsenwneswsenwswnenenw
swswswsweswswswseswnwswswswswswswswnesw
sewswswswwnwswnwswwwwwwswnwsesewsw
newnwseeneneeewseneswnenenenwenesee
eseneneneneseeeneweenweswswenwee
newswsesewswsewnwwnewneswwswnwsenww
eneneneeeewneswsewseeeenwnwnwnee
nesenwnweeswswnesesweseseseneswsesesw
swswneseswswsewswwswswneswswswseswseswsw
eneneeeseeeeeeweeeeeee
nenewnwneeneswseneneeswnenwswenenewne
swneseeneeeneneeeneeeeeweneeene
nwsenwwnwnwnwnwweswwnwsenwsenwnw
neeenenewneenese
ewsenwseseseeseseneseeeeseswewsese
nwnwsenenwnwnwwnwnwnwwsenwnwnwwsenwnw
neneseswnwnenwnwnwnenwnwnenwnenenenenenw
seseseseswswsenwwswswswswseseee
nenenwnwnwswnenenenenwnenwnenenenenene
nenesenenewnenwnenenwnwnwnwswnenenenwnenese
wswswswswswsweseswswswswswneswswswnwse
wwwnwnwnwwwsewnewnwwswsenenwww
eswswswsenenwsewseseeswseswnwnwnwswswsw
swswnwswewwneswwwwwwweswesww
swsweswswswswswswswswswswewneswswsewsw
wwsenwnwenwswnwnwnesesenenwnwnwsenenwnw
weeneneneenenweeneeseneseeenee
swwewwswwswsweswnewseneswwwswww
sewnwswnwwneswnwwneesewnewwnwewnw
wwwwwswwswwsewswwwswswwnenwww
neewneneenewswneeenwneeeneneswne
nwnenewnwsenwnesenwnenenwenwnenwnwnenwnw
swswswswswwwswsenwswswswwswswswneseswsw
wsewwwnwwwwwwwewnewwwnww
neeeseeneseseenwseseseeswnewseseseew
nwsenwneenwwnwwnwswnwnwwswwnwswneswew
wnwnwnewswnwnenwnwsewewwnwnwesenw
swwswwswnwswswswswweseswwneswswswsw
eeeeewnweseeeeeneeseseeeeenw
swneeeweeeseesew
wwwwwswswnewswswnenwwseneswwwse
nwseseseseseseseseseseeswneesesesesese
nwewwwnweneswswewswenwwweeseene
nwneneswnwneenenwswenwneswswenwnwnenenene
swwwswsenewseswnewnewwwswseswwswsw
nenenwnwnenwnwnenwnwneneeswnwnwnwnenene
nwnwwnwnwnwnenwnwnwnwnwnwnwnwwnwnwnwnwse
esenwnwwswnwneeswswseeenenwswneneene
eseseeseseeseseesesenwseseeeesee
nwenwwwnwenenwnwenwnwnwswnenwnwnwnwnw
eseenwseseseseswenwseseseseseeesesese
eeeeeeeeeeeeeswnwneeneene
wnwwwnwnwwnenwwwnwwwewswwwwnw
senwwneseseeseseseeseswwseenewsesesw
senwneseseseewseeweneseeseeeese
eeeeesweseswneswnweswnwnwenwneeww
nenenwswneeneeeeneeswneeeneeenenwe
nenwnenwnwnenwsenwnwnwwnenwnwnwnwnwnenw
eswnwenwsesesenwswenwnwswwnesenwswswswsw
seseseseseseseeseseseseseseweeeese
eswneenenwswewneeneneeneeeneee
sweswswswswwnwswsweswswswwswsww
swwwswswswwswwwnewwswswsewwsww
swsesesesesesesesesesesesesesesene
neneneneneneneeneneenewneneenenenene
neseswwswwswwwsewwwswswsenewwnew
swseneneseseswswswswseseswsesesesesesese
eswwswswwnwswenwsweswswswswnwwseswswsw
nenenenwnenenenenenwneneneneneneneenesw
nwnwewswnwneswseeewnwswseswenenwenw
wwwwnwnwwwnwwnwnwwweswnwwnwnww
nwnwnwnwnwnwnwnwnewnwswneswnwnenwsenw
wseseseseseseseseseesenese
senwswneswswswswswseswswswswseswsewswswse
eesesweneweeenwneeneeeesweeee
seeneseeeseeeenweeweeeewee
nenwnenweswneswnwnwne
neeneneeneneenewnenenesweeneenwene
seseseseseseseseseneseseesewsesesesesese
eswswsesenwnenwwnwswnwsenwnenwwnwnenee
nwnwnwwnwnwnwenwsewwenenwnwnwwswnw
wwnwnwnwwnwneswnw
nenwneneswnwnwneneneenenwneneenwnenew
swsewneswneswneswnweneese
eneeewneswnweneeseeeneneneenenene
sesewsewsweeneneeneneesenwewswsesw
seeenweseenweeseneeenweewesw
eenwwneeeeneeneeweneswnweeswne
neswwnewnwswswswweswwswwswsesw
sesenesewseseweseseseweneseseseese
eeenwneswsenwseswseseeeenwswenwew
nwnwneenenenwsweewnwnenwnenenewsewse
swswswwswswswswneswswswewswswswnwwww
swwnenenesenwesewnwswesesewnwesese
eseseseswewesesenweeseswnw
wswswswwwwwwswwswswswwwwwnew
nwseeseeeseseswseseseseseseesee
wsewseeeseeeeeeeneeneeseeeee
nenenewneneneneneneneneneneneneneenene
enenenwsenweenwswnwswswswswwswenwenwnw
nenwneneneswnwnenenenwnenw
eeewseseseeneeseeeseeenwswsee
enesweneswweeneenweeneneewsenewe
seswswswswseswswnwswseswswnwswswswswswsw
nwnwnenenenenenwswnenenenw
wwswwswwwwwwwwewwwswnwwww
eeeneseeweneneneeeneeneeenenee
nenewnenewneeneweneeneewnenenenene
seswenwseswswswswsewswswswswseneseswswse
nwnwnwwnwwwwnwnwnwnwnwnenwnwnwsewwnw
eseseseseswwseseeseesewseswseswswswnw
newwnenenenenwenenewswneswsenenesenese
nwnenesenenenwnesenwnenwnwnwnewnwnenwnenw
swesweswswswswswswwswswswswswswswswswswnw
nwnwswnenwnenenwnenwnenwnenw
nenenenenenenenenenenwneneeswnenenenene
nwewnwnwnwnwnesewswnenwnw
swswseseseseseswseeseswesesesesenwsenw
wwsewnenewnwwswwwwneswsenwwnww
neeesenenenenewneneeeneeeeneneene
wwwwwswsewnwww
seseeseseewneseseseesesesesesesesesese
swneweneeswneenwneswnenwneeenenene
eneeseeeeenenweeseneeenenwee
swnwwnwwsenwnesewswwnwnwnwenwnwnenwnw
swseseswseseseswseswsweseswsesesesenwsesw
wswnewswswswswwwwseww
seseseseseseseeenwseseseswseseseseesese
eeneseesenenewwenwsenenenenwenesewse
nwewwswswsweeswswwswwseswswwswsww
seswswswswswwwswswnewswswwewswswswsw
swseenenwnwnenewwsenenenewswneneese
wwwswenwwwswnwwseswsewnwseswwswne
senwseeeeseseseseseeseeeseswnwsesese
wnenewnenenenesenenenenenewsesenwnenene
neeeeeeeneseeeeeeenweeee
swswneswswswswswswneswswswswswwse
enwseswwswnwneswswswneeswswswswsesenwswsw
swnwsesewneseseseseseseswwsenesesw
seeeeeeenweeeneeeeene
eseswswseeswseswswwwse
newnenwswsenenweneneseenwsweeeewe
nwswseswswseesewseseseseswsenesesesese
enwneswseeswnenesewsenwswsenwseswswsw
swwsweneeseneenweseeeeeeewee
swwsewwwwwnwwwewwwwwwwnw
swneswswswswswwwswwnewswswwsewww
nenewneseenesewnwneswnenenenwnenenesene
neneenewsewseneenenenenenesenenwnenee
eseswneseeneneneweneeneneenewene
seeseseeseseseswseesenwnweseeeenw
enenwwnwswseewsewnwsewseesenesesese
nwwsenwwnwnwwwnwwwwwnwsewwnww
neeneeenewswneeseenenenenenweeswne
wsewneseswnwsenwseseneweseewseene
swswswswswswswswwswneswswswswswswswswsw
seeeenwseseseeeeseeseeeeseee
nwesenenwwnewwnwneenwweswnwsenenw
wnenwnenwsweneneseneneeswnenwnwnenesew
eeeseeeeeeseeeseeeeenwnwee
esenwwswwseweseseswseseseswseneeswnw
wnenenenwenwesewneneseseewnewnenese
nwnenwnenwnwnwnwnwwenenwnwnenwnwneswnw
eneneswnenenenwneneeeenenwneneswene
sewwwswswswwsewnwwswswneww
wwwswwswwwswwswwwwnewswseswsww
swswseseseseswswsewswesewseswseesesesw
senwnwwnwnwwwnwnwnwnwnwnwwnwnwswenww
wwewnwewsewwnwwnweseswswenesenw
neneneeeneeneneneneswneneeneeeswe
eeseneewesweeeseeeeeeeenwee
esenewnewnwneswneneneneeneneeeeee
wwnwwwwwwwsesewnwwwwwwswwsw
nenwseneesweneneneneswenenenwwsewnee
seswseswswnwnwswswsw
swneneenesewnwnwneneneswesewwnenenesw
neeneeeeweeneneneneneneneneenene
nenweneeeenwneneneseneeeneseneew
wswwneswswswsewswswswsenwswnesw
nwnwnenwnwnwnwswsenwwnwenwnwnesenwnwnwnw
senwnwwnwwswwnwwwnwnwnwwnwwnwwe
nenenwnwnwneneneenenenenwseswnwnenwneswnw
seeeseeeeseeeeeeeenwsewee
seseeseseseeeeeseneeseseewsesee
sesesewseseseseswswsweseswsewseswnesenwse
nwswnenwnwnwnwnwnwnwnwnwnwnwnwnwnwnw
nwnwnwnwnwnenwnwneenwsww
nenwneseneswnwneswnenwnenenwnwnenwnenwne
eneneneneneneweneneseneneeneneenenee
nwnwnwnwswnwnwesenenwneneswnwnwnwenwnenww
neneneneneneneneneneneneswnenenenenenesw
enwnewwswsesenwsenwsesweeeswnwnwse
neswwswswesenenwenenenenwswseeenwe
nwwnwnwnwsewnwnwwwwnenwnwnwsenwenw
swnwenwenweswswseswswwswwneswneswwwse
eeeeneeneneeeneeneeewnee
eeswseswseswswwwswneswwsweswswswne
swnwswswswswswwenwswswswswenewnwsewsw
nwwswnwnwwwneswnwwnwnwnwnewwnwwnww
nwswneeneewwewewneseseneseseswse
weneneeseneswwswswneeeeenwese
seneeseseeeseseewseeseeswsenwsee
swswswseswneseswsenwseseseseswsesesesesewse
nenenwwswwnwnwenweenwnwswsweswswsenw
nwnwnwnwnwnwnwnwnenwnwnwnwnenwnwnwsenwswsw
nwwwwnenwnwnwwnwnwwswnwwewnwnwsese
nwswseeseswsesesesenwsesesesesesese
seswseswswswnwsweswswnewswswnwswseswswsw
neseswwsewsewswwsweeswseeswne
swwwwnwnwenwwnwwwwwwnwwwwww
swwnenweneneewneeseneenenenenwseesene
nenenenenenwneneneswneneneneenenenenene
wnwnenwesenwnwnwwnwnwnwwnwwnwnwnwnww
wsesesesesesesesesesesesene
neneswnenwwnwnenwneenwnwnwnwnwnwnenwnw
wswsenwswsenenwnwseseseseesesesesenw
wwnwnwnwnwwnwneesesenwnwnwnwnwnwnwnw
nwenwneneneneswnenwnwnwnwnenwnwnenwnenw
eeneneesewneeeesenenenenewsenwene
sesesewneswseseseseswseseswse
sesenwsesesewseseeseeseseneseswesesese
nenwseswseseneseswwsesweseswnwsesesesesene
eseeseseeseesesesesesenweeewese
nwnenwwnwnwwnwsewnwwnwwwwnwwnww
swesenweeseseesewsesesesese
eeeneeeeeeneeenesewnenwswee
nenenweneeneneeewneseeneneneeenee
newswswwwwwwwsewwewswneswww
swswneswseswsweswnwwseeseswswswsewswswsw
ewwswswswneswwswswnwenwnweewesenw
wsenwnwsesewwnwnwwnewnwenenwnwnwwnw
nenwnwneneenenenenwnwnwnewsenenene
enenweswenwnenwswseeweeswseeeene
seeneseeeeeeseeweweeneenwee
enwnenweswnwnwswneswnenweseswnw
enwsenwswswnenewwseseeswwswnenenene
wnwsewenewnwwwwnwenwnwwwenwsenw
wswnwswswswswsenenwneneewesewswsewwnw
seseeewseeseseseeesesesenwseseseee
neeewenenwesenweeswnewwnwswswse
neenwnenwenwnwswswnwenewswneneswenwnw
nenenenesenenenenenewenee
eswseswwwwwnenwswwwsweewnwww
nenenenenwwenenenenenenwseswnesenewnwe
weeneneseneneneneneneneneneneenenene
sewseseswneseseswseswseesewnwseswseswnese
swswswswswswseswswseswneswswswwswsesesw
eeenwneneeeeeeeeswneneswnenee
sesenwsewneswseseweseseseeswswsewsene
seseseseseseswseseseeswsewsesenesenwe
wwswwswwwsenesww
wwnwnwwsenwwnwnenwnwnwnwnwseeswwe
swswwwswwwwwwswwwwseneeswwww
neswsweswnwswwswswwswswseswswswswswsw
sesesesesesewseseseseseesesesee
sesenwsweseenweenweswwseeneeesenwe
eeeeneeeesweeeeeeeeesweenw
esesesesesenwneweneeeseesesewsese
seseseneeeeeeweeseeseeesesese
wwnewwseswwswwwwswew
neswswswseswswseswswseswswwswswswswswswsw
seseseseswnesweswseneswsesesesewswsesese
seseseseseseseseneseseseseseswsesesewsesw
wnwneswswswseswswnwswwwwswswswsweww
neeeweeeeseeeeeneeeeneenee
nwswwwswnewnwswsenwwwwswwseeewe
swwwwwswewwwwnwwwnwwwewwnw
nwsenwnwnwnwnwwwnwnwnewnwnwnwnwsewnwnwne
wseeeewenesesenwweneeneeesesesww
swwwswswwswswneswwsewswwswwwswsw
nweeenenenwseewswnewsewenewsewe
swswseswswswswswswwswswswswseswswswneswsw
eeneeeneeeeeeseeneneweneeee
nenwsesenwnwnwnenwnwnwnwnwnwnewnenwnwnwnwnw
nwsweswswseseseseseswswswseseseseswswsesw
sesesenwenwewseeeseeseseneeeswnw
nwnwnenwewnwnwwwnwnwse
nwwnenwnwnenenenenwnenwnwnwneneseenewne
eseseesesesesenwnesweweneswneswwnw
nwnwwwwwenwnwnwsenwwww
nwnweneneenwsenenwnwwneneswnwnwwsenwnw
swseswsenwswnweseswseswsewseseeesw
neneneswnwnwseswwsenwnwwnwnwnenwnene
seeesewseneseseswsesesesenwseesesesee
senenweweseeneneeneswseeweseneww
eeeeeeweeeseeseeeneeeesee
eneseeeeeewneeeneeeeenene
wwewswsewwwwwnewwwsw
neeeeeeseeeeeeeeesweeee
swnwnwsewwwwwnwnwnwnenwenwnwneswnw
wseswswseseseswnenweswswsweseswseswse
wewnwswwswwwswswnewwwnwnewsewsw
nwnenwnenenwnwnenesenwneneseswwenenene
swenwneswsewenwwnwneswnwenwnwwswnwnwnw
senenenenewswneneneweswnenenenenenenwnene
swseseseswsesenwnesweseseeswnwsesenwsesw
swseseswneswswneswswswswswswnwneswseswse
nwwnwnwnwwnwwweswwnwnwwwnesenwenw
seeneswswswneenwesenwsenwwweeeswne
seseesesenwseeesesesweseseeeesese
senwnwswweseswnwneewwneenwnenenwsenw
swswwwwnwswwwseswsesewnwenwwwnese
neesenwnwnwnenenwnenewnenenenesenenwne
seswswswswsesesesesenwswseneswswswswseswsw
nenwwnwswneneenwnenenenwseeeswsenwnesw
eneneneeneneswnenenenenewsenenenenenene
nwswwwwsewnwwnwnenwnwwwewwsw
neneneneweeswseneneneenenenenenenenewne
ewwwwwwnenwnwwnwnwwesewnwnww
nenenenwnenenwneneneswnwnwnwnwnwneseneswne
wnwnwwwwsewnwwnwwwwnwsenwwwswe
neneeenwneneeneneeneneswnesweneew
wwnwnwwnwewnwwswewwwwnwwwww
eseeeeseeeenweenwweswseeee
nwnwnwwwnwnwnwswnwnwnwnwnewnwnww
eeenenenenenenesenenewneenenenenene
wswseswswewseneseewswnesenwswswnenw
nwwswnwnwnwnwwnwewwwnwnwnenwnwnwwswnw
nwsewneswwswswewswswswnwwnwseseswsw
seneneeeeeneeswneneswnwneenenenwne
sesenwsenwswseseseswseseswseswseseseene
eswswnenewweeseswwswneswwnenwseswne
wsweneesenewneswsenwnwsweneneneswnenw
nwnwnwnwnwenwnesewsenwswnwnwnwnwwnwnw
senwsewseseeseseswseswswswnwsenwseseesw
wswnwwswewwswswswwswswswswswswswsw
wnwneeswwnwnwnwwse
swswwswwwswswswwwswswwswswswneww
nwnwwnwwswnwwswenwwnewnwwwwnwnwe
seseseesesesesewseeeeseseesenesese
sesesesenwseeseseseseseseesese
swwwwnesenewnesw
senwseswwweseswswswseseseswseseswnesw
eeeenewewseeneeeeeseeseseese
eweeeneeeeeseneee
senwseseseswsesenwnesewwseseswsenwese
swsewswwwwnwwwwwwwwwwswwew
seeeeeseseesewesesesewseesesese
nenwnwnenwnwnwnwnwnwnwenwswnenwnw
swswswswswneswswswswsesweswswswswnwsww
seswsesesesesenwsesese
nenenenenesewneneneneswnenenenenenenenwne
swseeeeseeeeeeseeweeseesene
swsenwsewsenwsewenwseseswwnweseneese
nweneesweseesewseseswewsesese
neeseneneneneeseenwnenenenweenenee
wneeseeneeneeneeeenwneeneeenee
swnwnwnwnwnwnwnwswnwwwwwnwnwenewnw
esenwsesenesweeeseswsesesesesesesesese
seeeneneseeneweneeswnwneneeeewe
nesewswnwwweswswwwwswewswwww
wwwewenwnwnwnenwwnwnwnwnwswnwwwnwsw
nwnenwnwneseswwewswseesewwnwwnwsw
eeeneswesenenesweewneenwnenenwe
neswswswnwseseswseseseswewswswwneswsw
nenenenwnenenwnesenewnenenenenenenenene
wwnenwnewwnwnwswwwnwnwswnwnenwsewnw
nwneswswswwswswswswswwsewsw
seeswsenweesewneeenweneeswseeesw
neseswswseswsesesenwseeswsenesesesesww
weneeeeeeeeesweee
nwwwwwswwwwwwwnwwnwwwnwnew
nenewneneneneeewnwseseneneenewseswe
neswswwenenenwneswenwneswnwwswseswwswe
nwwnwnwnwnenwnwwwnwnwnwnwnwnenwnwsenwse
nwswenwwnwenwnwnwnwnwnwnwnwnwnwnwnwnw
nwwsewnwwwwsewnewwwwww
nenewneneneseneneeneneswnenwnenenwnwne
nwwsewnwnwnwnwsenwnwwwwwwnenenwnwwnw
seseswswswnwseswswswswswnweseseseswese
nwwnwsenwnwwnwwnwnwwnww
nenenwnenenwnwneenenwnenwnwnwwnenwnene
newewwewnwwsewweeeneswwwww
swnenwnwnwwseswsweswneswswesw
wwwwnwwnwnwnwwwwwwnwnwenwww
seswswwwnewnewwwnewnewwswwsww
eseswneweswneeeewnenw
eeneenewwweewenwswesenenwseww
wwwwwnwwsewwwswewwswswwswew
wesenwsesewewnwne
ewnwnwnewseswwseneneenenenenenwneenene
newwsewwwwwwwwnewneseswww
eeeeneneeneneswneneneneenenenee
enwwnwwwwnwewewwwwwnwwwww
newewnwswswwsenwesenenwewswswesw
nenwnwnenwnwnenwewnwwnwnenenwnwnwnwenw
neswnwnwnenenenwwswnenesesenenwnewnene
wwwnwwnwwwnwwnwnenwnwse
eneneneenwseneeweeesweeeewnee
swsesesenesenwesesesesesesewsesesesesesew
nweseeeeneswnweenweeswneeneee
nwnwnwnwnwnwnwseswnewnwnw
wnwneseenenwnenenenwnwnenenenenenwnenw
seseeeeeseweeseseseseseeseeenw
seseneswseseseseseseseseseseseseseseswse
eneenenenenenewneneewnenenenene
swswenwswswswswswsewswwwswswswwwswe
eseseseesenweseseeeswsenweseseee
wnwnwnwwnwwwnwnwnwnwnwnwnwwwsenwnw
wneeswneneneneeneneneneneneneneneene
seneeseswnwenwwnewsweseweseseseee
swwwwswewwswwswwwswwwwsww
wenwnwswnwwwwwnesenwnwnwsenwnwnenww
swswswswnewwenwnwswnewsesweswsesew
seswsesesesesesesesesesesesesesesenwnwsesee
swseswswswswswswneswswsw
swswenewnwnewnenwnwswnenwnwneseeseswesw
wwswwnwnwnwenwnwnwwwewwwenesw
nwwneeswnenenwneneenw
swseswwswswswswswwswswswswswswswswswnw
nenwnenwneseneneneneeneneeneswnenenee
seseswseseeswswswswswwswswswswswswseswnw
seseseeseneseeseseeesesesewseseesese
swwwwwwnwswswwwewwsewwwww
swwwwswswswswwewswswswsweswswnww
swswswseeswswsesewseswseseseswswsesesw
wnewsewswwwsewwnenwwsewwwwww
swseseswneswswsewswswswswswswswswswseswsw
seseseseswneswswneswswswswsesesesesewsesew
nwnwneswnenenwneeswneneenenenenenenenene
nenenenenwnwwnenenesenenesenwse
wneeneeneneneseneneeneneneneswneenene
newneneneesewneeneeenenesenenenenene
wseseseseseseseseseseseesenwseseseswnwe
nwwwswwnwnwnewwwnwwwwww
swseseseseseseswnwseseseseseeseseseseseswnw
nwnenwnenwenwswenwswnwnwnenwnenenwnenwnw
seeswsewwseseswseswseseswesesesesesesw
eeeeeeeeeewseenweseneee
seswseswswswnweswswswswswnwswswswswswswsw
wneeeeneeneneneneeneeeneeneee
newneneseeeeeneeeeweeeeeesew
wseswseneseeseeeseneseseesesenwse
swnweeeseneseenewwswesenwesweenw
newnwnenwnwnenwnwnenenenwnwnenenenwnwsene
nwswswswnenwsenwsewwneswseweseseww
wswwneewwwswww
sesesesesewneeseseswwwenesesesese
eeseeseeseneesewseseseeeeeesese
seeneeweesenesewwseeseeseswne
wswsenwsenenewnenewneeswsesesesesew
nenwwseneneswnenenenwneneneenwenwnene
seseenwseeseseseesenwseseeeeseeee
nenenesenweeeneeeneneneneneneneee
seseseewseseseseswswseseseseseeseseswnw
enwnwswswwswwwsenwneeesenweewswsesw
seseseseseneeseseseseseweeeweese
swwwswewwswnwswswswswswwswswwswswsw
swsesesesenwswsewesesenwseeswsenwsesese
neneneneswneeneeeenwneneswnenwnenene
senwewwswnweseneneswneeswnweswwe
enenwnenenwnewnwnwnenenw
swneswswsewwswswnewneeswnesweswswsw
seseseswenwnwseeswswneseenwneseeswsw
nenwwwwsenwwww
wwswswewwwnwnwwsewnweswewnwnww
nwnesenwneneneneenenewnenewseneneesene
eseeneneneneeeneneewneneeeenee
nesesewswseneesesesweseseeeenesewse
newswwsenwswswwswwwswewswwwwswne
wwswenwswswwswwswswwwewwswswsww
wswsweseseesenesenwseeseneseesenwsee
wseenweesesesenenwseeseseseeseesesw
wnwwsewwwewswwswswwswwwnewsw
enesewneenewswnenenesenenenenenenenw
wswswswswwnewswnwsweswsw
swswseswswswswswswswswswswswswswneswswse
wwswswnwswswseswswnewswseswnesw
seswsenwswseswnwseswswswswsenwseeeswwse
senenenenwnwewnenenwnenwneneneweseswne
"""

tinput2 = """
sesenwnenenewseeswwswswwnenewsewsw
neeenesenwnwwswnenewnwwsewnenwseswesw
seswneswswsenwwnwse
nwnwneseeswswnenewneswwnewseswneseene
swweswneswnenwsewnwneneseenw
eesenwseswswnenwswnwnwsewwnwsene
sewnenenenesenwsewnenwwwse
wenwwweseeeweswwwnwwe
wsweesenenewnwwnwsenewsenwwsesesenwne
neeswseenwwswnwswswnw
nenwswwsewswnenenewsenwsenwnesesenew
enewnwewneswsewnwswenweswnenwsenwsw
sweneswneswneneenwnewenewwneswswnese
swwesenesewenwneswnwwneseswwne
enesenwswwswneneswsenwnewswseenwsese
wnwnesenesenenwwnenwsewesewsesesew
nenewswnwewswnenesenwnesewesw
eneswnwswnwsenenwnwnwwseeswneewsenese
neswnwewnwnwseenwseesewsenwsweewe
wseweeenwnesenwwwswnew
"""

const dim = 500
const (ox, oy) = 100, 100

tilestrings = filter(x -> length(x) > 3,  split(tinput, "\n"))

function parsetilestring(str::AbstractString)
    rows, cols = 0, 0
    for t in map(m -> m.match, eachmatch(r"[ns]?[ew]", str))
        if t == "e"
            cols += 1
        elseif t == "w"
            cols -= 1
        elseif t == "ne"
            rows -= 1
            cols += 1
        elseif t == "se"
            rows += 1
        elseif t == "sw"
            cols -= 1
            rows += 1
        elseif t == "nw"
            rows -= 1
        end
    end
    return rows, cols
end

identify!(s, mat) = begin r, c = parsetilestring(s) .+ [ox, oy]; mat[r, c] = !mat[r, c] end

function part1()
    tmat = zeros(Bool, dim, dim)
    for s in tilestrings
        identify!(s, tmat)
    end
    bsum = sum(values(tmat))
    println("Part 1: ", bsum)
    return tmat
end

const tilematrix = part1()

function adjacent(row, col)
    return [[row, col] .+ x for x in [[0, 1], [1, 0], [1, -1], [0, -1], [-1, 0], [-1, 1]]]
end

function daystep!(mat)
    cmat = deepcopy(mat)
    nrows, ncols = size(mat)
    for c in 10:ncols-10, r in 10:nrows-10
        nsum = sum([mat[i, j] for (i, j) in adjacent(r, c)])
        if mat[r, c]
            (nsum == 0 || nsum > 2) && (cmat[r, c] = false)
        elseif nsum == 2
             cmat[r, c] = true
        end
    end
    mat .= cmat
end

function part2()
    for i in 1:100
        daystep!(tilematrix)
    end
    println("Part 2: ", sum(tilematrix))
end

@time part2()
